language: python
python:
- 3.8
- 3.7
# - 3.6
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: jirvingphd
  password:
    secure: P2+o4IG2GmpXljts0hr0OltBI1OVavoD9uHR3oBEXM+kPcX3icwVndxiYSKMeNqn/tLVUJiLmjUFtmbYjBBZo5NRGdhO2/DCZz09+p4J/kPBGpcNiuLmVy2db+P4SxobQdXDaKgmsnLqYxQUw2nsv6uwBDyGk4i6Ew3lDoPp6vyRV+wmNiI5kyl9p+eoX/JQrvRwfpPH0xUSi69CO6byEh7As7JXHppgMAx4Qv4cQQaDzJ3GvoQ/0PJw2oPaZpjNFZseqwt46RZxS4Yuekou8HJ5V9osC+IAis+SPyKPsPirdKqLPQ72NJWctP+T0OgGSyywJe3Ab5LNpY8ZytIvePsozIxkOsTwV+nacuoyrqnkuhf4gNWVH6bOFf4GdcjqbBzoLm+FgDow1hlhRO5h3O8Iry9qgrtHnJMqE4zVlMUaQHObFjbPs5x1s97TXTcdYUpcYHqKMxRE1UBdrcyor/E7vzTmx+hTxNCDvjKaLWql97yRWUhQn7ggfwCB0DN+8f6vgF0hWdXFcGsyijBZLT2xlgre5RiVp9sIg7aachNlh5TlYXvlxEP27ACxQW2BbJjysiK8//4X5DWG7EmJOKfRy9UZXTU6dU9qTtemG5Qzp4FNFjvVLEIlYOoPOW3sMdiR1Uvi//3dnVwHpQsfJJUdnSUl6GWzCYBw3VC7yJo=
  on:
    # tags: true
    repo: jirvingphd/fsds
    python: 3.7 #3.6
